<?php

use Illuminate\Database\Seeder;

class AnexosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$anexo=[
    		['nombre' => 'Guardia '
, 'numero' => '101',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Personal Secr '
, 'numero' => '102',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Personal Licencias    '
, 'numero' => '103',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Personal Pagos    '
, 'numero' => '104',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejales Secre  '
, 'numero' => '105',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejales 1  '
, 'numero' => '106',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejales 2  '
, 'numero' => '107',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejales 3  '
, 'numero' => '108',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Omil Secre    '
, 'numero' => '109',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Omil Jefe '
, 'numero' => '110',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Turismo Jefe  '
, 'numero' => '111',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Turismo Secre '
, 'numero' => '112',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Rentas Secre  '
, 'numero' => '113',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Rentas Jefe   '
, 'numero' => '114',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fiscalizacion Jefe    '
, 'numero' => '115',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fiscalizadores    '
, 'numero' => '116',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transito Secre    '
, 'numero' => '117',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transito Jefe '
, 'numero' => '118',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transito Licencias    '
, 'numero' => '119',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Org Comun Secre   '
, 'numero' => '120',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Org Comun Jefe    '
, 'numero' => '121',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Tesoreria Secre   '
, 'numero' => '122',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Tesoreria Jefe    '
, 'numero' => '123',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Tesoreria B Garantia  '
, 'numero' => '124',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Partes    '
, 'numero' => '125',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Jefe Movilizacion '
, 'numero' => '126',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Compras Jefe  '
, 'numero' => '127',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secretario Transito   '
, 'numero' => '128',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Sicotecnico   '
, 'numero' => '129',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Jefa Personal '
, 'numero' => '130',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Compras Otro  '
, 'numero' => '131',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Sala Reunion P1   '
, 'numero' => '132',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OOCC Terreno  '
, 'numero' => '133',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Turismo A '
, 'numero' => '134',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Informaciones '
, 'numero' => '135',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Caja  '
, 'numero' => '136',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Finanzas Secre    '
, 'numero' => '201',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Finanzas Jefe '
, 'numero' => '202',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Finanzas central  '
, 'numero' => '203',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Finanzas Director '
, 'numero' => '204',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Administracion Secre  '
, 'numero' => '205',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Administrador '
, 'numero' => '206',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Control Secre '
, 'numero' => '207',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Control Fiscal    '
, 'numero' => '208',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Control Director  '
, 'numero' => '209',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Sala de reuniones '
, 'numero' => '210',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Informatica Jefe  '
, 'numero' => '211',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRPP  '
, 'numero' => '212',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac Secre '
, 'numero' => '213',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac Jefe  '
, 'numero' => '214',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac MValenz   '
, 'numero' => '215',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac PMB   '
, 'numero' => '216',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras Secre   '
, 'numero' => '217',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras Ingeniero   '
, 'numero' => '218',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras Proyecto    '
, 'numero' => '219',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras Director    '
, 'numero' => '220',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Informatica   '
, 'numero' => '221',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'CAFETERIA '
, 'numero' => '222',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac Proyectos '
, 'numero' => '223',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin Asistente   '
, 'numero' => '224',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRPP Jefe '
, 'numero' => '225',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras Fiscalizacion   '
, 'numero' => '226',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac Presupuesto   '
, 'numero' => '227',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Aseo y Ornato '
, 'numero' => '228',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin C Asistente '
, 'numero' => '229',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Sala de Servidores    '
, 'numero' => '248',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Bienestar '
, 'numero' => '301',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Segurito  '
, 'numero' => '302',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRPP Jefe '
, 'numero' => '303',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Medio Ambiente Jefe   '
, 'numero' => '304',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juridico Secre    '
, 'numero' => '305',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juridico Jefe '
, 'numero' => '306',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secretaria Secre  '
, 'numero' => '307',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secretario    '
, 'numero' => '308',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Dideco Secre  '
, 'numero' => '309',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Dideco Jefe   '
, 'numero' => '310',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Adulto Mayor  '
, 'numero' => '311',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Alcaldia Secre    '
, 'numero' => '312',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Alcalde   '
, 'numero' => '313',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transparencia '
, 'numero' => '314',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Medio Ambiente Sec    '
, 'numero' => '315',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Medio Ambiente Jefe   '
, 'numero' => '316',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Pandora Aviso '
, 'numero' => '399',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Social Secre  '
, 'numero' => '401',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Social Jefe   '
, 'numero' => '402',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Social SUF    '
, 'numero' => '403',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Social Pasis  '
, 'numero' => '404',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Vivienda Secre    '
, 'numero' => '405',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Vivienda Jefe '
, 'numero' => '406',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juzgado Secre '
, 'numero' => '407',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juzgado Abogado   '
, 'numero' => '408',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fomento Secre '
, 'numero' => '409',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fomento Jefe  '
, 'numero' => '410',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Opera Secre   '
, 'numero' => '412',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Opera Electrico   '
, 'numero' => '413',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Opera Jefe    '
, 'numero' => '414',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Puente Jefe   '
, 'numero' => '415',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Puente Secretaria '
, 'numero' => '416',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Bodega    '
, 'numero' => '417',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Movilizacion  '
, 'numero' => '418',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OPD Secre '
, 'numero' => '419',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Opd JEFE  '
, 'numero' => '420',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Jefas de Hogar    '
, 'numero' => '421',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OIRS  '
, 'numero' => '422',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Vinculos Secre    '
, 'numero' => '423',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Vinculos Secre    '
, 'numero' => '424',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Senda Sec '
, 'numero' => '425',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Senda Jefe    '
, 'numero' => '426',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fomento Asesor    '
, 'numero' => '427',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Senama 1  '
, 'numero' => '428',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Senama 2  '
, 'numero' => '429',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Adulto Mayor Sec  '
, 'numero' => '430',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Adulto Mayor Jefe '
, 'numero' => '431',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'ChileCrece    '
, 'numero' => '432',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Asistente Social  '
, 'numero' => '433',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'FPS Secre '
, 'numero' => '434',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'FPS Jefe  '
, 'numero' => '435',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'FPS 1 '
, 'numero' => '436',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'FPS 2 '
, 'numero' => '437',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Sexualidad    '
, 'numero' => '438',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Operadora L1  '
, 'numero' => '501',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Operadora L2  '
, 'numero' => '502',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Informatica Secre '
, 'numero' => '504',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Informatica   '
, 'numero' => '510',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac C Sec '
, 'numero' => '511',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secplac C Jefe    '
, 'numero' => '512',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Finanzas C Dir    '
, 'numero' => '513',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Finanzas C Sec    '
, 'numero' => '514',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Turismo C Jefe    '
, 'numero' => '515',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Operaciones C Jefe    '
, 'numero' => '516',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Operaciones C Sec '
, 'numero' => '517',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Operaciones C Armando '
, 'numero' => '518',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Jefe C Deportes   '
, 'numero' => '519',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Cultura C '
, 'numero' => '520',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Social C Sec  '
, 'numero' => '521',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Social C Jefe '
, 'numero' => '522',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'SecMuni C Sec '
, 'numero' => '523',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Secretario Municipal C    '
, 'numero' => '524',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Compras C Cristian    '
, 'numero' => '525',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Compras C Jefe    '
, 'numero' => '526',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'EGIS C    '
, 'numero' => '527',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Areas Verdes  '
, 'numero' => '528',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OOCC C Sec    '
, 'numero' => '529',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OOCC C Jefe   '
, 'numero' => '530',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Servicios Generales C '
, 'numero' => '531',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fiscalizacion C   '
, 'numero' => '532',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin Salud   '
, 'numero' => '533',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras C Sec   '
, 'numero' => '534',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Obras C Jefe  '
, 'numero' => '535',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juridco C Sec '
, 'numero' => '536',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juridico I Neira  '
, 'numero' => '537',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Rentas C  '
, 'numero' => '538',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin C JC Franz  '
, 'numero' => '539',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin C Asistente '
, 'numero' => '540',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin Muni C  '
, 'numero' => '541',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Admin C Sec   '
, 'numero' => '542',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRPP C P Peralta  '
, 'numero' => '543',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRPP Jefe '
, 'numero' => '544',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Juzgado Policia C '
, 'numero' => '545',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Fomento C Jefe    '
, 'numero' => '546',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Prodesal C Sec    '
, 'numero' => '547',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRHH C Sec    '
, 'numero' => '548',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRHH C Licencias  '
, 'numero' => '549',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'RRHH C Jefe   '
, 'numero' => '550',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Movilizacion  '
, 'numero' => '551',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OMIL C    '
, 'numero' => '552',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Mujer Jefa Hogar C    '
, 'numero' => '553',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transparencia C   '
, 'numero' => '554',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Puente C Sec  '
, 'numero' => '556',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Puente C Jefe '
, 'numero' => '557',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Ficha PS C    '
, 'numero' => '558',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transito C Sec    '
, 'numero' => '559',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Transito C Jefe   '
, 'numero' => '560',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'SENDA C   '
, 'numero' => '561',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'DIDECO C Sec  '
, 'numero' => '562',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'DIDECO C Jefe '
, 'numero' => '563',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Tesoreria C   '
, 'numero' => '564',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Partes C  '
, 'numero' => '565',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Vivienda C    '
, 'numero' => '566',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Bienestar C   '
, 'numero' => '567',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'OPD C '
, 'numero' => '568',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejales C Sec  '
, 'numero' => '569',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejal C F Gonzales '
, 'numero' => '570',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejal C M Sepulveda    '
, 'numero' => '571',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejal C LM Ramirez '
, 'numero' => '572',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejal C O Rojas    '
, 'numero' => '573',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Concejal C P Hernandez    '
, 'numero' => '574',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'DIDEL '
, 'numero' => '575',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Control C '
, 'numero' => '576',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Alcaldia C Chofer '
, 'numero' => '577',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Alcaldia C    '
, 'numero' => '578',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Alcalde   '
, 'numero' => '579',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],
['nombre' => 'Rentas C  '
, 'numero' => '580',
'created_at' => \Carbon\Carbon::now()->toDateTimeString()],

        ];

        DB::table('anexos')->insert($anexo);
    }
}